# Generated by Django 2.0.6 on 2019-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_inspect', '0002_auto_20190403_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectdevinfo',
            name='dev_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='设备状态'),
        ),
    ]
