# Generated by Django 2.0.6 on 2018-11-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='问题标题')),
                ('hot', models.CharField(max_length=30, verbose_name='问题热度')),
                ('answer_count', models.IntegerField(max_length=30, verbose_name='回答数')),
                ('text', models.CharField(max_length=30, verbose_name='回答内容')),
                ('author', models.CharField(max_length=30, verbose_name='回答作者')),
                ('voteup_count', models.IntegerField(max_length=30, verbose_name='赞同数量')),
                ('comment_count', models.IntegerField(max_length=30, verbose_name='评论数量')),
                ('update_time', models.DateTimeField(max_length=30, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知乎问题表',
                'verbose_name_plural': '知乎问题表',
            },
        ),
    ]
