# Generated by Django 2.0.6 on 2018-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='问题标题')),
                ('hot', models.CharField(max_length=30, verbose_name='问题热度')),
                ('answer_count', models.IntegerField(verbose_name='回答数')),
            ],
            options={
                'verbose_name': '知乎问题表',
                'verbose_name_plural': '知乎问题表',
            },
        ),
        migrations.AlterModelOptions(
            name='datainfo',
            options={'verbose_name': '回答详情', 'verbose_name_plural': '回答详情'},
        ),
        migrations.RemoveField(
            model_name='datainfo',
            name='answer_count',
        ),
        migrations.RemoveField(
            model_name='datainfo',
            name='hot',
        ),
    ]
