# Generated by Django 2.0.6 on 2018-11-16 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0002_auto_20181116_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainfo',
            name='question',
        ),
        migrations.AddField(
            model_name='datainfo',
            name='question_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='问题标题'),
            preserve_default=False,
        ),
    ]
