# Generated by Django 2.0.6 on 2018-11-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0003_auto_20181116_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spider_data.DataList', verbose_name='问题标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datalist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
