# Generated by Django 2.0.6 on 2018-12-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0006_auto_20181210_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=30, verbose_name='排行类型')),
                ('classifi', models.CharField(max_length=30, verbose_name='店铺类型')),
                ('class_id', models.IntegerField(verbose_name='排行类型id')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('shopId', models.CharField(max_length=30, verbose_name='店铺id')),
                ('shopName', models.CharField(max_length=30, verbose_name='店铺名')),
                ('mainRegionName', models.CharField(max_length=30, verbose_name='所在区域')),
                ('taste', models.FloatField(verbose_name='口味')),
                ('environment', models.FloatField(verbose_name='环境')),
                ('service', models.FloatField(verbose_name='服务')),
                ('avgPrice', models.IntegerField(verbose_name='平均消费')),
                ('city_id', models.IntegerField(verbose_name='城市id')),
                ('address', models.CharField(max_length=30, verbose_name='地址')),
                ('update_time', models.DateField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大众点评店铺排行表',
                'verbose_name_plural': '大众点评店铺排行表',
            },
        ),
    ]
