# Generated by Django 2.0.6 on 2018-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0007_foodrank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrank',
            old_name='class_id',
            new_name='tip_id',
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='avgPrice',
            field=models.IntegerField(blank=True, verbose_name='平均消费'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='environment',
            field=models.FloatField(blank=True, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='mainRegionName',
            field=models.CharField(blank=True, max_length=30, verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='service',
            field=models.FloatField(blank=True, verbose_name='服务'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='taste',
            field=models.FloatField(blank=True, verbose_name='口味'),
        ),
    ]
