# Generated by Django 2.0.6 on 2018-12-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0009_auto_20181210_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrank',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='地址'),
        ),
    ]
