# Generated by Django 2.0.6 on 2018-12-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_data', '0010_auto_20181210_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrank',
            name='classifi',
            field=models.CharField(max_length=100, verbose_name='店铺类型'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='mainRegionName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在区域'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='shopId',
            field=models.CharField(max_length=100, verbose_name='店铺id'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='shopName',
            field=models.CharField(max_length=100, verbose_name='店铺名'),
        ),
        migrations.AlterField(
            model_name='foodrank',
            name='tip',
            field=models.CharField(max_length=100, verbose_name='排行类型'),
        ),
    ]
