# Generated by Django 2.0.6 on 2018-11-08 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('host_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostserviceinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='hostserviceinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_management.HostInfo', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='hostserviceinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='se_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_db', to='host_management.DatabaseInfo', verbose_name='数据库'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='grant_db',
            field=models.ManyToManyField(to='host_management.DatabaseDBInfo', verbose_name='授权库'),
        ),
        migrations.AddField(
            model_name='databaseuserinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='add_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_host', to='host_management.HostInfo', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='databaseinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='databasedbinfo',
            name='add_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_db_add_user', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='databasedbinfo',
            name='db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_db_db', to='host_management.DatabaseInfo', verbose_name='数据库'),
        ),
    ]
