# Generated by Django 2.0.6 on 2018-12-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_management', '0003_auto_20181221_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_update_user', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
    ]
